### ISSUE TITLE
I have some input didn't want to be delete or add.

### ISSUE THREAD

**Issue by yujulchen** [MrHertal/react-admin-json-view#14]
Hi 💦
Is there any solution to control deletable and addable? 
Can it work like react-json-view's demo, let enable add/delete = false then hover it'll not show icons?
<img width="637" alt="螢幕快照 2021-07-14 下午21 42 16 下午" src="https://user-images.githubusercontent.com/74940804/125632707-19573755-f7e9-4810-900b-471ad6be6109.png">

I have some input that didn't want to be delete or add.
I had tried to use onDelete or onAdd in reactJsonOptions but didn't work...

**Comment by MrHertal** [comment]
Hi,

you can use all the options that react json view offers in the `reactJsonOptions` props.

**Comment by yujulchen** [comment]
Hi
I tried to use it like this but the delete icon is still on there.
```
        <JsonInput
          source="source"
          defaultValue={{...}}
          reactJsonOptions={{
            name: "name",
            collapsed: true,
            enableClipboard: false,
            displayDataTypes: true,
            onDelete: false,
          }}
        />
```
<img width="111" alt="螢幕快照 2021-07-27 下午19 27 43 下午" src="https://user-images.githubusercontent.com/74940804/127146379-eedbe382-00be-4ecc-b76f-61e9b7d2af2a.png">

ReactJsonOptions seems should work like the react-json-view demo's defaults?
https://github.com/mac-s-g/react-json-view/blob/7c154b9a7d83ea89dce2c171ebdf4d163ff49233/demo/src/js/components/Demo.js#L23-L36

**Comment by MrHertal** [comment]
Hi, you are right there was a bug with the props `onAdd`, `onEdit` and `onDelete`

It's now fixed by [this release](https://github.com/MrHertal/react-admin-json-view/releases/tag/v1.2.1).
