### ISSUE TITLE
Missing prop-types for mini-create-react-context/dist/esm

### ISSUE THREAD

**Issue by shunyun-bp** [MrHertal/react-admin-json-view#2]
Installed and first use gets this error:
Failed to compile

Module not found: Can't resolve 'prop-types' in '/Users/seanonion/code/playground/demosim-admin/ds-admin/node_modules/mini-create-react-context/dist/esm'

**Comment by shunyun-bp** [comment]
Seem to have solved this by adding react-json-view to the npm install statement.  ie:

> npm install -s react-json-view react-admin-json-view

**Comment by MrHertal** [comment]
Hi,

I could not reproduce on an a new project. Which npm version are you using?
You should not install react-json-view manually because it is a dependency of react-admin-json-view.
