### ISSUE TITLE
JsonField text is unreadable on dark theme in React-Admin

### ISSUE THREAD

**Issue by car1ot** [MrHertal/react-admin-json-view#21]
**[Issue Description]**
Currently, the JsonField component in React-Admin does not handle the current theme properly. When a dark theme is set, the text within the JsonField appears black, making it extremely difficult to read. This issue affects the readability of the JsonField component, limiting its usability to only the white theme.

**[Proposed Improvement]**
JsonField should be updated to ensure proper handling of the current theme in React-Admin. Specifically, when a dark theme is applied, the text within the JsonField should be adjusted to a more readable color, allowing users to view the content regardless of the selected theme. This enhancement will improve the overall usability and accessibility of the JsonField component in different theme settings.

**Comment by jerkwithinjerks** [comment]
Adjust props.reactJsonOptions.theme according to your current theme.
you can find existing theme here https://mac-s-g.github.io/react-json-view/demo/dist/

**Comment by car1ot** [comment]
[Issue solution explained]
@jerkwithinjerks provided api to change the theme of `JsonField`.
