### ISSUE TITLE
Support string json fields via an option

### ISSUE THREAD

**Issue by notz** [MrHertal/react-admin-json-view#6]
It would be very helpful to support fields with stringified json. So unparsed to view and stringified after edit.

**Comment by MrHertal** [comment]
You are right, I will work on this soon

**Comment by MrHertal** [comment]
I added `jsonString` argument to both components. It's a boolean that tells if you want to save a JSON string.

https://github.com/MrHertal/react-admin-json-view/releases/tag/v1.1.0
